#####################################
# NAME : SWATI BOTUWAR              #
# Z- ID : Z1828087                  #
# CSCI/689/SECTION 1                #
# TA NAME : NITHIN DEVANG           #
# ASSIGNMENT NUMBER : 1             #
# DUE DATE : FRIDAY, 27 JANUARY 2017#
#####################################

assign1 : assign1.o
	g++ -o assign1 assign1.o -lm

assign1.o : assign1.cc
	g++ -c -Wall -Werror assign1.cc 

clean : 
	-rm *.o assign1
